services:
  # ─── Zookeeper + Kafka ─────────────────────────────────────
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ─── PostgreSQL + Flyway ───────────────────────────────────
  postgres:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-migrate:
    image: flyway/flyway:9
    depends_on:
      - postgres
    env_file: .env
    command: >
      -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      migrate
    volumes:
      - ./db:/flyway/sql

  # ─── ClickHouse ────────────────────────────────────────────
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"    # HTTP интерфейс
      - "9001:9000"    # Native TCP (на хост 9001)
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  # ─── MinIO (S3) ────────────────────────────────────────────
  minio:
    image: minio/minio:latest
    command: server /data
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  # ─── Spark cluster ─────────────────────────────────────────
  spark-master:
    image: bitnami/spark:3.3.1
    environment:
      SPARK_MODE: master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - spark_logs:/opt/bitnami/spark/logs

  spark-worker:
    image: bitnami/spark:3.3.1
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    ports:
      - "8081:8081"
    volumes:
      - spark_logs:/opt/bitnami/spark/logs

  # ─── FastAPI + Kafka producer (Dev1) ───────────────────────
  api:
    build: ./api
    env_file: .env
    volumes:
      - ./api/src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - kafka
      - clickhouse
      - minio

  # ─── Spark batch ingestion (Dev2) ──────────────────────────
  spark-batch:
    build:
      context: .  # только папка ingestion
      dockerfile: ingestion/Dockerfile
    env_file: .env
    depends_on:
      - spark-master
      - spark-worker
      - postgres
      - minio

  # ─── Spark Structured Streaming (Dev2) ─────────────────────
  spark-stream:
    build: 
      context: .
      dockerfile: streaming/Dockerfile
    env_file: .env
    depends_on:
      - spark-master
      - spark-worker
      - kafka
      - minio
      - clickhouse
    restart: unless-stopped

volumes:
  pgdata:
  clickhouse_data:
  minio_data:
  spark_logs:
